resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/sbodiu-pivotal/flight-school
    branch: master

- name: staging-app
  type: cf
  source:
    api: http://api.local.pcfdev.io
    username: admin
    password: admin
    organization: pcfdev-org
    space: pcfdev-space

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml
  - put: staging-app
    params:
      manifest: flight-school/manifest.yml
